import { ChevronRightIcon } from "@chakra-ui/icons";
import clsx from "clsx";
import { useRouter } from "next/router";
import React from "react";
import styles from "../../assets/css/pages/policy.module.css";
import Footer from "../../components/Footer";
import Navbar from "../../components/Navbar";
const Payment = () => {
  const router = useRouter();
  return (
    <div>
      <Navbar />
      <div className="distance">
        <div className={styles.bgProductRedirect}>
          <div className="grid wide">
            <div className="row">
              <div className="col l-12 c-12 m-12">
                <div className={styles.productNameAndBrand}>
                  <div className={styles.redirectContainer}>
                    <p
                      className={clsx(styles.redirectName, styles.home)}
                      onClick={() => router.push("/")}
                    >
                      Trang chủ
                    </p>
                    <ChevronRightIcon className={styles.redirectIcon} />
                    <p className={styles.redirectName}>chính sách thanh toán</p>
                  </div>
                </div>
                <div className={styles.body}>
                  <p
                    dangerouslySetInnerHTML={{
                      __html: content,
                    }}
                  />

                  <div className="row">
                    <div className="col l-6 l-o-3 m-6 m-o-3 c-8 c-o-2">
                      <div className={styles.footer}>
                        <p>
                          Chân thành cảm ơn quý khách đã đọc những thông tin
                          này, kính chúc quý khách có những giây phút mua sắm
                          thật thoải mái.Nếu có bất cứ thắc mắc nào, kính mong
                          quý khách hãy liên hệ với Admin để được giải đáp,
                          Chúng tôi rất hân hạnh được phục vụ quý khách!
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default Payment;

const content = `

<p style="margin: 0in; margin-bottom: .0001pt; line-height: 150%; background: #FCFCFC; vertical-align: baseline;"><span style="font-size: 20pt; line-height: 150%; font-family: Roboto; color: #1a202c; border: none windowtext 1.0pt; padding: 0in;">CH&Iacute;NH S&Aacute;CH THANH TO&Aacute;N</span></p>
<p style="margin: 0in; margin-bottom: .0001pt; line-height: 150%; background: #FCFCFC; vertical-align: baseline; box-sizing: border-box; overflow-wrap: break-word; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit;"><span style="font-family: Roboto; color: #1a202c; border: none windowtext 1.0pt; padding: 0in;">Để đảm bảo đơn h&agrave;ng được ho&agrave;n th&agrave;nh tốt nhất, ch&uacute;ng t&ocirc;i th&agrave;nh thật k&iacute;nh mong qu&yacute; kh&aacute;ch thanh to&aacute;n trước một phần gi&aacute; trị của mỗi đơn h&agrave;ng.</span></span></p>
<p style="margin: 0in; margin-bottom: .0001pt; line-height: inherit; background: #FCFCFC; vertical-align: baseline; box-sizing: border-box; overflow-wrap: break-word; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-size: 12pt;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit;"><span style="font-family: Roboto; color: #1a202c; border: none windowtext 1.0pt; padding: 0in;">C&aacute;c bước mua h&agrave;ng sẽ được thực hiện theo tr&igrave;nh tự như sau:</span></span></span></p>
<p style="margin: 0in; margin-bottom: .0001pt; line-height: inherit; background: #FCFCFC; vertical-align: baseline; box-sizing: border-box; overflow-wrap: break-word; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-size: 12pt;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit;"><span style="font-family: Roboto; color: #1a202c; border: none windowtext 1.0pt; padding: 0in;">&nbsp;</span></span></span></p>
<p style="margin: 0in; margin-bottom: .0001pt; line-height: 150%; background: #FCFCFC; vertical-align: baseline; box-sizing: border-box; overflow-wrap: break-word; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit;"><span style="font-family: Roboto; color: #1a202c; border: none windowtext 1.0pt; padding: 0in;">&nbsp;</span></span></p>
<p style="margin: 0in; margin-bottom: .0001pt; line-height: inherit; background: #FCFCFC; vertical-align: baseline; box-sizing: border-box; overflow-wrap: break-word; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="font-size: 12pt;"><strong style="box-sizing: border-box; overflow-wrap: break-word; font-style: inherit; font-variant: inherit; font-stretch: inherit; line-height: inherit;"><span style="box-sizing: border-box; overflow-wrap: break-word;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit;"><span style="font-family: Roboto; color: #1a202c; border: none windowtext 1.0pt; padding: 0in;">I:C&Aacute;C BƯỚC THANH TO&Aacute;N</span></span></span></strong></span></p>
<p style="margin: 0in; margin-bottom: .0001pt; line-height: 150%; background: #FCFCFC; vertical-align: baseline; box-sizing: border-box; overflow-wrap: break-word; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-size: 12pt;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit;"><span style="font-family: Roboto; color: #1a202c; border: none windowtext 1.0pt; padding: 0in;">&nbsp;-Nếu qu&yacute; kh&aacute;ch đ&atilde; chọn được sản phẩm ưng &yacute;, qu&yacute; kh&aacute;ch h&atilde;y nhấn v&agrave;o n&uacute;t thanh to&aacute;n hoặc c&oacute; thể để sản phẩm ở giỏ h&agrave;ng.</span></span></span></p>
<p style="margin: 0in; margin-bottom: .0001pt; line-height: 150%; background: #FCFCFC; vertical-align: baseline; box-sizing: border-box; overflow-wrap: break-word; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-size: 12pt;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit;"><span style="font-family: Roboto; color: #1a202c; border: none windowtext 1.0pt; padding: 0in;">&nbsp;-Trong trang thanh to&aacute;n,qu&yacute; kh&aacute;ch vui l&ograve;ng điền đầy đủ th&ocirc;ng tin của người nhận h&agrave;ng.</span></span></span></p>
<p style="margin: 0in; margin-bottom: .0001pt; line-height: 150%; background: #FCFCFC; vertical-align: baseline; box-sizing: border-box; overflow-wrap: break-word; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-size: 12pt;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit;"><span style="font-family: Roboto; color: #1a202c; border: none windowtext 1.0pt; padding: 0in;">&nbsp;-Qu&yacute; kh&aacute;ch c&oacute; thể chuyển khoản theo số t&agrave;i khoản được cung cấp b&ecirc;n dưới mỗi trang thanh to&aacute;n, nh&acirc;n vi&ecirc;n cửa h&agrave;ng sẽ gọi v&agrave;o số điện thoại được cung cấp để x&aacute;c nhận đơn h&agrave;ng.</span></span></span></p>
<p style="margin: 0in; margin-bottom: .0001pt; line-height: 150%; background: #FCFCFC; vertical-align: baseline; box-sizing: border-box; overflow-wrap: break-word; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-size: 12pt;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit;"><span style="font-family: Roboto; color: #1a202c; border: none windowtext 1.0pt; padding: 0in;">&nbsp;</span>-Nếu qu&aacute; 24h kể từ thời gian đặt nhưng đơn h&agrave;ng vẫn chưa được trả trước, đơn h&agrave;ng sẽ bị hủy.</span></span></p>
<p style="margin: 0in; margin-bottom: .0001pt; line-height: 150%; background: #FCFCFC; vertical-align: baseline; box-sizing: border-box; overflow-wrap: break-word; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-size: 12pt;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit;"><span style="font-family: Roboto; color: #1a202c; border: none windowtext 1.0pt; padding: 0in;">&nbsp;</span>-Sau khi thanh to&aacute;n trước th&agrave;nh c&ocirc;ng,qu&yacute; kh&aacute;ch sẽ nhận được h&oacute;a đơn hiển thị t&igrave;nh trạng đơn h&agrave;ng, h&oacute;a đơn c&oacute; đầy đủ th&ocirc;ng tin bao gồm cả ph&iacute; thanh to&aacute;n trước.(H&oacute;a đơn nằm ở mục th&ocirc;ng tin người d&ugrave;ng).</span></span></p>
<p style="margin: 0in; margin-bottom: .0001pt; line-height: 150%; background: #FCFCFC; vertical-align: baseline; box-sizing: border-box; overflow-wrap: break-word; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-size: 12pt;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit;"><span style="font-family: Roboto; color: #1a202c; border: none windowtext 1.0pt; padding: 0in;">&nbsp;</span>-Trường hợp qu&yacute; kh&aacute;ch kh&ocirc;ng đăng nhập, ch&uacute;ng t&ocirc;i xin ph&eacute;p được gửi t&igrave;nh trạng đơn h&agrave;ng qua t&agrave;i khoản mạng x&atilde; hội để qu&yacute; kh&aacute;ch nắm bắt được t&igrave;nh trạng đơn h&agrave;ng một c&aacute;ch tốt nhất.</span></span></p>
<p style="line-height: 150%; background: #FCFCFC; vertical-align: baseline; box-sizing: border-box; overflow-wrap: break-word; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px; margin: 0in 0in .0001pt .25in;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-size: 12pt;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit;"><span style="font-family: Roboto; color: #1a202c; border: none windowtext 1.0pt; padding: 0in;">&nbsp;</span></span></span></p>
<p style="margin: 0in; margin-bottom: .0001pt; line-height: inherit; background: #FCFCFC; vertical-align: baseline; box-sizing: border-box; overflow-wrap: break-word; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="font-size: 12pt;"><strong style="box-sizing: border-box; overflow-wrap: break-word; font-style: inherit; font-variant: inherit; font-stretch: inherit; line-height: inherit;"><span style="box-sizing: border-box; overflow-wrap: break-word;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit;"><span style="font-family: Roboto; color: #1a202c; border: none windowtext 1.0pt; padding: 0in;">II:CHI TIẾT PH&Iacute; THANH TO&Aacute;N</span></span></span></strong></span></p>
<p style="margin: 0in; margin-bottom: .0001pt; line-height: 150%; background: #FCFCFC; vertical-align: baseline; box-sizing: border-box; overflow-wrap: break-word; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-size: 12pt;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit;"><span style="font-family: Roboto; color: #1a202c; border: none windowtext 1.0pt; padding: 0in;">&nbsp;</span>-Với đơn h&agrave;ng nhập từ mỹ:25% tổng gi&aacute; trị đơn h&agrave;ng.</span></span></p>
<p style="margin: 0in; margin-bottom: .0001pt; line-height: 150%; background: #FCFCFC; vertical-align: baseline; box-sizing: border-box; overflow-wrap: break-word; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-size: 12pt;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit;"><span style="font-family: Roboto; color: #1a202c; border: none windowtext 1.0pt; padding: 0in;">&nbsp;</span>-Với đơn h&agrave;ng nhập từ h&agrave;n quốc:15% tổn gi&aacute; trị đơn h&agrave;ng.</span></span></p>
<p style="margin: 0in; margin-bottom: .0001pt; line-height: 150%; background: #FCFCFC; vertical-align: baseline; box-sizing: border-box; overflow-wrap: break-word; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-size: 12pt;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit;"><span style="font-family: Roboto; color: #1a202c; border: none windowtext 1.0pt; padding: 0in;">&nbsp;-Với đơn h&agrave;ng c&oacute; chứa c&aacute;c sản phẩm nhập từ nhiều quốc gia kh&aacute;c nhau,ph&iacute; thanh to&aacute;n trước sẽ t&iacute;nh theo quốc gia c&oacute; ph&iacute; thanh to&aacute;n cao nhất.</span></span></span></p>
<p style="margin: 9.6pt 0in 9.6pt 0in;">&nbsp;</p>

 `;
