import { ChevronRightIcon } from '@chakra-ui/icons'
import clsx from 'clsx'
import { useRouter } from 'next/router'
import React from 'react'
import styles from "../../assets/css/pages/policy.module.css"
import Footer from '../../components/Footer'
import Navbar from '../../components/Navbar'
const ReturnProduct = () => {
    const router = useRouter()
  return (
   <div>
       <Navbar/>
       <div className="distance">
        <div className={styles.bgProductRedirect}>

        <div className="grid wide">
          <div className="row">
            <div className="col l-12 c-12 m-12">
              <div className={styles.productNameAndBrand}>
               
                <div className={styles.redirectContainer}>
                  <p className={clsx(styles.redirectName,styles.home)}  onClick={() =>
                      router.push("/")
                    }>
                    Trang chủ
                  </p>
                  <ChevronRightIcon className={styles.redirectIcon} />
                  <p className={styles.redirectName}>
                    Chính sách đổi trả
                  </p>
                  
                </div>
              </div>
              <div className={styles.body}>
                  <p
                    dangerouslySetInnerHTML={{
                      __html: content,
                    }}
                  />

                  <div className="row">
                    <div className="col l-6 l-o-3 m-6 m-o-3 c-8 c-o-2">
                      <div className={styles.footer}>
                        <p>
                          Chân thành cảm ơn Bạn đã đọc những thông tin
                          này, kính chúc Bạn có những giây phút mua sắm
                          thật thoải mái.Nếu có bất cứ thắc mắc nào, kính mong
                          Bạn hãy liên hệ với Admin để được giải đáp,
                          Chúng tôi rất hân hạnh được phục vụ Bạn!
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
            </div>
          </div>
          
          </div>
         
        </div>
       </div>
       <Footer/>
   </div>
  )
}

export default ReturnProduct

const content = `

<p style="margin: 0in; margin-bottom: .0001pt; background: #FCFCFC; vertical-align: baseline;"><em><span style="font-size: 20.0pt; font-family: Roboto; color: #1a202c; border: none windowtext 1.0pt; padding: 0in;">CH&Iacute;NH S&Aacute;CH ĐỔI TRẢ</span></em></p>
<p style="margin: 0in; margin-bottom: .0001pt; line-height: 16.9pt; background: #FCFCFC; vertical-align: baseline;"><em><span style="font-size: 10.0pt; font-family: 'Calibri',sans-serif; color: #1a202c;">&nbsp;</span></em></p>
<p style="margin: 0in; margin-bottom: .0001pt; line-height: 16.9pt; background: #FCFCFC; vertical-align: baseline; box-sizing: border-box; overflow-wrap: break-word; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><em style="box-sizing: border-box; overflow-wrap: break-word;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit;"><strong><span style="font-family: Roboto; color: #1a202c; border: none windowtext 1.0pt; padding: 0in;">Đối với sản phẩm nước ngo&agrave;i:</span></strong></span></em></p>
<p style="margin: 0in; margin-bottom: .0001pt; line-height: 16.9pt; background: #FCFCFC; vertical-align: baseline; box-sizing: border-box; overflow-wrap: break-word; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit;"><span style="font-family: Roboto; color: #1a202c; border: none windowtext 1.0pt; padding: 0in;">&nbsp; -li&ecirc;n hệ Admin để giải quyết vấn đề đổi trả</span></span></p>
<p style="margin: 0in; margin-bottom: .0001pt; line-height: 16.9pt; background: #FCFCFC; vertical-align: baseline; box-sizing: border-box; overflow-wrap: break-word; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit;"><span style="font-size: 10.0pt; font-family: 'inherit',serif; color: #1a202c; border: none windowtext 1.0pt; padding: 0in;">&nbsp;</span></span></p>
<p style="margin: 0in; margin-bottom: .0001pt; line-height: 16.9pt; background: #FCFCFC; vertical-align: baseline; box-sizing: border-box; overflow-wrap: break-word; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><em style="box-sizing: border-box; overflow-wrap: break-word;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit;"><strong><span style="font-family: Roboto; color: #1a202c; border: none windowtext 1.0pt; padding: 0in;">Đối với sản phẩm trong nước:</span></strong></span></em></p>
<p style="margin: 0in; margin-bottom: .0001pt; line-height: 16.9pt; background: white; vertical-align: baseline; box-sizing: border-box; overflow-wrap: break-word; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit;"><u><span style="font-family: Roboto; color: black; border: none windowtext 1.0pt; padding: 0in;">C&aacute;c trường hợp được đổi lại h&agrave;ng h&oacute;a:</span></u></span></p>
<p style="margin: 0in; margin-bottom: .0001pt; line-height: 16.9pt; background: white; vertical-align: baseline; box-sizing: border-box; overflow-wrap: break-word; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit;"><span style="font-family: Roboto; color: black; border: none windowtext 1.0pt; padding: 0in;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; -Trường hợp sản phẩm bị lỗi do nh&agrave; sản xuất, sản phẩm k&eacute;m chất lượng, sản phẩm kh&ocirc;ng đ&uacute;ng chủng loại, mẫu m&atilde;, số lượng như đ&atilde; đặt h&agrave;ng, Qu&yacute; kh&aacute;ch kh&ocirc;ng h&agrave;i l&ograve;ng chất lượng &ndash; Qu&yacute; kh&aacute;ch sẽ được đổi sản phẩm kh&aacute;c hoặc trả lại m&agrave; kh&ocirc;ng mất khoản ph&iacute; n&agrave;o.</span></span></p>
<p style="margin: 0in; margin-bottom: .0001pt; line-height: 16.9pt; background: white; vertical-align: baseline; box-sizing: border-box; overflow-wrap: break-word; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit;"><span style="font-family: Roboto; color: black; border: none windowtext 1.0pt; padding: 0in;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Sản phẩm đổi phải đảm bảo chưa được sử dụng, đối với h&agrave;ng Full seal th&igrave; phải c&ograve;n nguy&ecirc;n seal, đối với c&aacute;c sản phẩm Gift Set, Tester phải đảm bảo c&ograve;n nguy&ecirc;n hộp, sản phẩm chưa bị can thiệp v&agrave; sử dụng. sản phẩm sẽ được ch&uacute;ng t&ocirc;i kiểm tra lại để đảm bảo sản phẩm l&agrave; h&agrave;ng h&oacute;a của b&ecirc;n ch&uacute;ng t&ocirc;i ph&acirc;n phối.</span></span></p>
<p style="margin: 0in; margin-bottom: .0001pt; line-height: 16.9pt; background: white; vertical-align: baseline; box-sizing: border-box; overflow-wrap: break-word; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit;"><span style="font-family: Roboto; color: black; border: none windowtext 1.0pt; padding: 0in;">&nbsp;</span></span></p>
<p style="margin: 0in; margin-bottom: .0001pt; line-height: 16.9pt; background: white; vertical-align: baseline; box-sizing: border-box; overflow-wrap: break-word; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit;"><u><span style="font-family: Roboto; color: black; border: none windowtext 1.0pt; padding: 0in;">C&aacute;c trường hợp kh&ocirc;ng được &aacute;p dụng đổi lại h&agrave;ng h&oacute;a:</span></u></span></p>
<p style="margin: 0in; margin-bottom: .0001pt; line-height: 16.9pt; background: white; vertical-align: baseline; box-sizing: border-box; overflow-wrap: break-word; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit;"><span style="font-family: Roboto; color: black; border: none windowtext 1.0pt; padding: 0in;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Sản phẩm kh&ocirc;ng phải do Gentlevn.com cung cấp, kh&ocirc;ng chứng minh được nguồn gốc của sản phẩm (h&oacute;a đơn, thời gian mua h&agrave;ng).&nbsp;</span></span></p>
<p style="margin: 0in; margin-bottom: .0001pt; line-height: 16.9pt; background: white; vertical-align: baseline; box-sizing: border-box; overflow-wrap: break-word; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit;"><span style="font-family: Roboto; color: black; border: none windowtext 1.0pt; padding: 0in;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Sản phẩm được mua qu&aacute; 7 ng&agrave;y kể từ khi sản phẩm được b&aacute;n ra.</span></span></p>
<p style="margin: 0in; margin-bottom: .0001pt; line-height: 16.9pt; background: white; vertical-align: baseline; box-sizing: border-box; overflow-wrap: break-word; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit;"><span style="font-family: Roboto; color: black; border: none windowtext 1.0pt; padding: 0in;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Sản phẩm bị t&aacute;c động từ ph&iacute;a người sử dụng dẫn đến hư hỏng, m&oacute;p m&eacute;o, thay đổi h&igrave;nh dạng.</span></span></p>
<p style="margin: 0in; margin-bottom: .0001pt; line-height: 16.9pt; background: white; vertical-align: baseline; box-sizing: border-box; overflow-wrap: break-word; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit;"><span style="font-family: Roboto; color: black; border: none windowtext 1.0pt; padding: 0in;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Sản phẩm đ&atilde; được sử dụng</span></span></p>
<p style="margin: 0in; margin-bottom: .0001pt; line-height: 16.9pt; background: white; vertical-align: baseline; box-sizing: border-box; overflow-wrap: break-word; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit;"><span style="font-family: Roboto; color: black; border: none windowtext 1.0pt; padding: 0in;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Ch&uacute;ng t&ocirc;i kh&ocirc;ng chấp nhận trả lại h&agrave;ng, ho&agrave;n lại tiền với c&aacute;c trường hợp muốn trả lại h&agrave;ng v&igrave; l&yacute; do kh&ocirc;ng th&iacute;ch m&ugrave;i, thay đổi &yacute; định, hay c&aacute;c l&yacute; do c&aacute; nh&acirc;n kh&aacute;c.</span></span></p>
<p style="margin: 0in; margin-bottom: .0001pt; line-height: 16.9pt; background: white; vertical-align: baseline; box-sizing: border-box; overflow-wrap: break-word; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit;"><span style="font-family: Roboto; color: black; border: none windowtext 1.0pt; padding: 0in;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Kh&ocirc;ng bảo h&agrave;nh lỗi chai/v&ograve;i xịt do nh&agrave; sản xuất</span></span></p>
<p style="margin: 0in; margin-bottom: .0001pt; line-height: 16.9pt; background: white; vertical-align: baseline; box-sizing: border-box; overflow-wrap: break-word; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit;"><span style="font-family: Roboto; color: black; border: none windowtext 1.0pt; padding: 0in;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Kh&ocirc;ng bảo h&agrave;nh đối với sản phẩm nước hoa mini ( &lt;= 20ml )</span></span></p>
<p style="margin: 0in; margin-bottom: .0001pt; line-height: 16.9pt; background: white; vertical-align: baseline; box-sizing: border-box; overflow-wrap: break-word; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit;"><span style="font-family: Roboto; color: black; border: none windowtext 1.0pt; padding: 0in;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Kh&ocirc;ng đổi trả lotion, sữa tắm, lăn khử m&ugrave;i</span></span></p>
<p style="margin: 0in; margin-bottom: .0001pt; line-height: 16.9pt; background: white; vertical-align: baseline; box-sizing: border-box; overflow-wrap: break-word; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit;"><span style="font-family: Roboto; color: black; border: none windowtext 1.0pt; padding: 0in;">&nbsp;</span></span></p>
<p style="margin: 0in; margin-bottom: .0001pt; line-height: 16.9pt; background: white; vertical-align: baseline; box-sizing: border-box; overflow-wrap: break-word; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit;"><u><span style="font-family: Roboto; color: black; border: none windowtext 1.0pt; padding: 0in;">Quy tr&igrave;nh đổi h&agrave;ng h&oacute;a:</span></u></span></p>
<p style="margin: 0in; margin-bottom: .0001pt; line-height: 16.9pt; background: white; vertical-align: baseline; box-sizing: border-box; overflow-wrap: break-word; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit;"><span style="font-family: Roboto; color: black; border: none windowtext 1.0pt; padding: 0in;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Sau khi bạn đ&aacute;p ứng được c&aacute;c điều kiện về đổi lại h&agrave;ng h&oacute;a của ch&uacute;ng t&ocirc;i, h&atilde;y li&ecirc;n hệ với ch&uacute;ng t&ocirc;i để được hỗ trợ.</span></span></p>
<p style="margin: 0in; margin-bottom: .0001pt; line-height: 16.9pt; background: white; vertical-align: baseline; box-sizing: border-box; overflow-wrap: break-word; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="box-sizing: border-box; overflow-wrap: break-word; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit;"><span style="font-family: Roboto; color: black; border: none windowtext 1.0pt; padding: 0in;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Sau khi tiếp nhận th&ocirc;ng tin v&agrave; check kiểm c&aacute;c điều kiện, nếu bạn đ&aacute;p ứng đủ điều kiện, ch&uacute;ng t&ocirc;i sẽ hỗ trợ ngay v&agrave; nhanh nhất cho bạn.</span></span></p>

`